kind: Service
apiVersion: v1
metadata:
  name: mqtt-broker
spec:
  selector:
    app: mqtt-broker
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
  type: ClusterIP
  sessionAffinity: ClientIP
